"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import {
  BookingHeader,
  BookingSidebar,
} from "@/components/booking-flow";

export default function BookingConfirmationPage() {
  const searchParams = useSearchParams();

  const reference = searchParams.get("reference") ?? "KIA-VP-2024-X9Z";
  const scheduledAt = searchParams.get("scheduledAt");
  const serviceName = searchParams.get("serviceName") ?? "15,000 Mile Precision Inspection";
  const agencyName = searchParams.get("agencyName") ?? "Kia Downtown Velocity";
  const agencyCity = searchParams.get("agencyCity") ?? "Downtown District";
  const vehicleName = searchParams.get("vehicleName") ?? "Kia EV6 GT-Line";
  const plate = searchParams.get("plate") ?? "VELOCITY-01";
  const vinTail = searchParams.get("vinTail") ?? "8829";

  const appointmentDate = scheduledAt
    ? new Date(scheduledAt).toLocaleDateString("en-US", {
        weekday: "short",
        month: "short",
        day: "numeric",
      })
    : "Mon, Nov 15";

  const appointmentTime = scheduledAt
    ? new Date(scheduledAt).toLocaleTimeString("en-US", {
        hour: "2-digit",
        minute: "2-digit",
      })
    : "09:30 AM";

  async function downloadReceiptPdf() {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("KIA SERVICE - BOOKING RECEIPT", 20, 20);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`Confirmation ID: ${reference}`, 20, 34);
    doc.text(`Vehicle: ${vehicleName}`, 20, 44);
    doc.text(`Plate: ${plate}`, 20, 54);
    doc.text(`VIN (tail): ${vinTail}`, 20, 64);
    doc.text(`Service: ${serviceName}`, 20, 74);
    doc.text(`Agency: ${agencyName}`, 20, 84);
    doc.text(`City: ${agencyCity}`, 20, 94);
    doc.text(`Appointment Date: ${appointmentDate}`, 20, 104);
    doc.text(`Appointment Time: ${appointmentTime}`, 20, 114);

    doc.setFontSize(10);
    doc.text("Generated by KIA VELOCITY booking platform.", 20, 132);

    doc.save(`kia-receipt-${reference}.pdf`);
  }

  return (
    <>
      <BookingHeader
        title="Confirmation"
        context={{ reference, scheduledAt: scheduledAt ?? undefined, serviceName, agencyName, agencyCity, vehicleName, plate, vinTail }}
        currentStep="confirmation"
        backHref="/"
        backLabel="Home"
      />

      <BookingSidebar
        context={{ reference, scheduledAt: scheduledAt ?? undefined, serviceName, agencyName, agencyCity, vehicleName, plate, vinTail }}
        currentStep="confirmation"
      />

      <main className="mx-auto max-w-[1440px] px-4 py-12 md:px-12 lg:ml-72 lg:max-w-[calc(1440px+18rem)]">
        <header className="mb-16 flex flex-col justify-between gap-8 md:flex-row md:items-end">
          <div className="max-w-3xl">
            <div className="mb-4 flex items-center gap-4">
              <div className="primary-gradient flex h-12 w-12 items-center justify-center rounded-full shadow-[0_0_40px_rgba(166,200,255,0.2)]">
                <span className="material-symbols-outlined material-filled text-3xl text-on-primary">check_circle</span>
              </div>
              <span className="font-headline text-sm font-bold uppercase tracking-widest text-primary">Booking Confirmed</span>
            </div>
            <h1 className="mb-4 font-headline text-5xl font-bold leading-none tracking-tight md:text-7xl">
              YOU&apos;RE ALL SET FOR <br />
              <span className="text-primary-fixed-dim">THE FAST LANE.</span>
            </h1>
            <p className="max-w-xl text-lg text-on-surface-variant">
              Confirmation ID: <span className="font-mono font-bold text-on-surface">{reference}</span>
            </p>
          </div>

          <div className="flex flex-wrap gap-4">
            <button className="flex items-center gap-2 rounded-lg border border-outline-variant/20 bg-surface-container-high px-8 py-4 font-headline font-bold uppercase tracking-tight transition-all hover:bg-surface-variant">
              <span className="material-symbols-outlined text-xl">calendar_add_on</span>
              Add to Calendar
            </button>
            <Link
              href={`/track?reference=${encodeURIComponent(reference)}`}
              className="primary-gradient rounded-lg px-8 py-4 font-headline font-bold uppercase tracking-tight text-on-primary shadow-lg transition-all active:scale-95"
            >
              Track My Appointment
            </Link>
            <Link
              href="/"
              className="rounded-lg border border-outline-variant/20 bg-surface-container px-8 py-4 font-headline font-bold uppercase tracking-tight transition-all hover:bg-surface-variant"
            >
              Back to Home
            </Link>
            <Link
              href="/book"
              className="rounded-lg border border-primary/30 bg-primary/10 px-8 py-4 font-headline font-bold uppercase tracking-tight text-primary transition-all hover:bg-primary/20"
            >
              Book Another Service
            </Link>
          </div>
        </header>

        <div className="grid grid-cols-1 gap-8 lg:grid-cols-12">
          <section className="space-y-8 lg:col-span-8">
            <div className="glass-card group relative overflow-hidden rounded-xl border border-white/5">
              <div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-primary/10 to-transparent opacity-50" />
              <div className="relative p-8 md:p-12">
                <div className="flex flex-col gap-12 md:flex-row">
                  <div className="flex-shrink-0">
                    <div className="aspect-video w-full overflow-hidden rounded-lg bg-surface-container-lowest md:w-64">
                      <img
                        alt="Kia EV6"
                        className="h-full w-full object-cover grayscale transition-all duration-700 group-hover:grayscale-0"
                        src="https://lh3.googleusercontent.com/aida-public/AB6AXuDEyVB9LKosA2c38ZdTFBVxJRpL8adcU7VOjHttN-XzLn21Thi0o0_rHP_MUei-mUd2uXSVTSdiNBjthFd3ZmLjvO10B38lEWM4En64_5MhQF3X_jzBNzQTT5Kdd63srFLf-FDlZ-bNiu33ItR-tZ3YshlJaVDjp1huO4eJJDvLAobVM8wLZS2IFpKChbYFxpp9P0TTb0X3dTBmodVhqqhIaRVZzOinNNxvdZ58pKOU4fZAmshdHx3W4m1GN9uOh9WOv1a_Dq5oJK4"
                      />
                    </div>
                    <div className="mt-6">
                      <h3 className="font-headline text-2xl font-bold uppercase tracking-tight">{vehicleName}</h3>
                      <p className="font-label text-sm uppercase tracking-widest text-on-surface-variant">Plate: {plate}</p>
                    </div>
                  </div>

                  <div className="flex-grow space-y-8">
                    <div>
                      <label className="mb-2 block font-label text-xs font-bold uppercase tracking-widest text-primary">Service Package</label>
                      <h4 className="font-headline text-2xl font-bold">{serviceName}</h4>
                      <p className="mt-2 text-sm leading-relaxed text-on-surface-variant">
                        Full system diagnostic, battery health optimization, high-performance fluid replacement, and rotor calibration.
                      </p>
                    </div>
                    <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
                      <div>
                        <label className="mb-2 block font-label text-xs font-bold uppercase tracking-widest text-primary">Date &amp; Time</label>
                        <div className="flex items-center gap-3">
                          <span className="material-symbols-outlined text-on-surface-variant">event</span>
                          <span className="font-headline text-lg font-semibold">{appointmentDate} • {appointmentTime}</span>
                        </div>
                      </div>
                      <div>
                        <label className="mb-2 block font-label text-xs font-bold uppercase tracking-widest text-primary">Agency</label>
                        <div className="flex items-center gap-3">
                          <span className="material-symbols-outlined text-on-surface-variant">location_on</span>
                          <span className="font-headline text-lg font-semibold">{agencyName}</span>
                        </div>
                        <p className="ml-7 text-xs text-on-surface-variant">{agencyCity}</p>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="mt-12 flex items-center justify-between border-t border-white/10 pt-8">
                  <button
                    onClick={downloadReceiptPdf}
                    className="flex items-center gap-2 font-label text-xs font-bold uppercase tracking-widest text-on-surface-variant transition-colors hover:text-white"
                  >
                    <span className="material-symbols-outlined text-lg">download</span>
                    Download Receipt
                  </button>
                  <div className="flex h-12 w-32 items-center justify-center rounded bg-white/5 opacity-30">
                    <span className="material-symbols-outlined">barcode_scanner</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="rounded-xl bg-surface-container-low p-8 md:p-12">
              <h2 className="mb-12 font-headline text-3xl font-bold tracking-tight">WHAT&apos;S NEXT?</h2>
              <div className="relative">
                <div className="absolute bottom-0 left-6 top-0 w-0.5 bg-surface-variant md:left-1/2 md:-ml-px" />
                <div className="space-y-16">
                  <div className="relative flex w-full flex-col items-center md:flex-row md:justify-between">
                    <div className="hidden w-5/12 pr-12 text-right md:block">
                      <h4 className="font-headline text-xl font-bold">Arrive &amp; Drop-off</h4>
                      <p className="mt-2 text-sm text-on-surface-variant">Check in via the app or at our contactless concierge kiosk. No paperwork required.</p>
                    </div>
                    <div className="primary-gradient z-10 flex h-12 w-12 items-center justify-center rounded-full shadow-[0_0_20px_rgba(0,91,170,0.4)]">
                      <span className="font-bold text-on-primary">01</span>
                    </div>
                    <div className="mt-4 pl-12 md:mt-0 md:w-5/12">
                      <div className="md:hidden">
                        <h4 className="font-headline text-xl font-bold">Arrive &amp; Drop-off</h4>
                        <p className="mt-2 text-sm text-on-surface-variant">Check in via the app or at our contactless concierge kiosk.</p>
                      </div>
                      <span className="font-label text-xs font-bold uppercase tracking-widest text-primary">ETA: 5 MINS</span>
                    </div>
                  </div>

                  <div className="relative flex w-full flex-col items-center md:flex-row md:justify-between">
                    <div className="order-2 mt-4 w-5/12 pr-12 text-left md:order-1 md:mt-0 md:text-right">
                      <span className="font-label text-xs font-bold uppercase tracking-widest text-secondary">LIVE UPDATES</span>
                      <div className="mt-2 md:hidden">
                        <h4 className="font-headline text-xl font-bold">Diagnostic HUD</h4>
                        <p className="mt-2 text-sm text-on-surface-variant">Watch a live feed of your vehicle&apos;s health check and approve recommendations in real-time.</p>
                      </div>
                    </div>
                    <div className="z-10 flex h-12 w-12 items-center justify-center rounded-full border-2 border-primary-fixed-dim bg-surface-container-high">
                      <span className="font-bold text-primary">02</span>
                    </div>
                    <div className="order-3 hidden w-5/12 pl-12 md:block">
                      <h4 className="font-headline text-xl font-bold">Diagnostic HUD</h4>
                      <p className="mt-2 text-sm text-on-surface-variant">Watch a live feed of your vehicle&apos;s health check and approve recommendations in real-time.</p>
                    </div>
                  </div>

                  <div className="relative flex w-full flex-col items-center md:flex-row md:justify-between">
                    <div className="hidden w-5/12 pr-12 text-right md:block">
                      <h4 className="font-headline text-xl font-bold">Premium Collection</h4>
                      <p className="mt-2 text-sm text-on-surface-variant">Your EV6 will be fully charged and detailed. Pick up with a single tap from your smartphone.</p>
                    </div>
                    <div className="z-10 flex h-12 w-12 items-center justify-center rounded-full border border-outline-variant bg-surface-container-high">
                      <span className="font-bold text-on-surface-variant">03</span>
                    </div>
                    <div className="mt-4 pl-12 md:mt-0 md:w-5/12">
                      <div className="md:hidden">
                        <h4 className="font-headline text-xl font-bold">Premium Collection</h4>
                        <p className="mt-2 text-sm text-on-surface-variant">Your EV6 will be fully charged and detailed. Pick up with a single tap.</p>
                      </div>
                      <span className="font-label text-xs font-bold uppercase tracking-widest text-on-surface-variant">COMPLETION: 1:30 PM</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <aside className="space-y-6 lg:col-span-4">
            <h3 className="px-2 font-headline text-lg font-bold uppercase tracking-widest text-primary-fixed-dim">Your Membership Perks</h3>

            <div className="rounded-xl border border-white/5 bg-surface-container p-6 transition-colors hover:bg-surface-container-high">
              <div className="flex items-start gap-4">
                <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-secondary/10 text-secondary">
                  <span className="material-symbols-outlined text-2xl">directions_car</span>
                </div>
                <div>
                  <h4 className="font-headline text-lg font-bold">Valet Status: Active</h4>
                  <p className="mt-1 text-sm text-on-surface-variant">Our team will be ready at the curb to take your vehicle upon arrival.</p>
                </div>
              </div>
            </div>

            <div className="rounded-xl border border-white/5 bg-surface-container p-6 transition-colors hover:bg-surface-container-high">
              <div className="flex items-start gap-4">
                <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-tertiary/10 text-tertiary">
                  <span className="material-symbols-outlined text-2xl">coffee</span>
                </div>
                <div>
                  <h4 className="font-headline text-lg font-bold">Velocity Lounge</h4>
                  <p className="mt-1 text-sm text-on-surface-variant">Complimentary Wi-Fi, premium refreshments, and workstation pods available while you wait.</p>
                </div>
              </div>
            </div>

            <div className="rounded-xl border border-white/5 bg-surface-container p-6 transition-colors hover:bg-surface-container-high">
              <div className="flex items-start gap-4">
                <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10 text-primary">
                  <span className="material-symbols-outlined text-2xl">verified_user</span>
                </div>
                <div>
                  <h4 className="font-headline text-lg font-bold">Kia Protection</h4>
                  <p className="mt-1 text-sm text-on-surface-variant">12-month guarantee on all precision parts and labor included with this service.</p>
                </div>
              </div>
            </div>

            <div className="group relative aspect-[4/3] overflow-hidden rounded-xl">
              <img
                alt="Diagnostic preview"
                className="absolute inset-0 h-full w-full object-cover brightness-50 transition-transform duration-700 group-hover:scale-105"
                src="https://lh3.googleusercontent.com/aida-public/AB6AXuCDKDVcEkH-Myr4zl73SdC2f9P8izfM23PEuAvq5ex-cqcU1TBeUYyuLbOmdZ4oYTX_JCzyofXWdlMOPcvJIYlp_HBE2gb1nkstHmFg9WbRi00Bi8oR3lHtl27yPOW_3mVA2ELCm1ES43_pEvfRVbuU7t-bgx9JcfG02gjQIQz_c6JLAKKx7m_7R4LUdV3orIF4GEmUK1Tiv7V8p-tW0vWtOPN4vQ2-AVImm637UbKudtQJM3tJhE9mxy3Ta97bBw1fWUEzP9ISxe4"
              />
              <div className="absolute inset-0 flex flex-col justify-end bg-gradient-to-t from-background to-transparent p-6">
                <span className="mb-2 font-label text-[10px] font-bold uppercase tracking-[0.2em] text-primary">Exclusive Feature</span>
                <h4 className="font-headline text-xl font-bold">Diagnostic HUD</h4>
                <p className="mt-2 text-xs text-on-surface-variant">Real-time telemetry and health reports direct to your device.</p>
              </div>
            </div>
          </aside>
        </div>
      </main>

      <footer className="mt-20 w-full border-t border-white/5 bg-[#0d141c]">
        <div className="mx-auto flex max-w-[1440px] flex-col items-center justify-between gap-4 px-12 py-8 md:flex-row">
          <div className="font-body text-xs uppercase tracking-widest text-gray-500">© 2024 KIA MOTORS. THE KINETIC ATELIER.</div>
          <div className="flex gap-8">
            <Link className="font-body text-xs uppercase tracking-widest text-gray-500 transition-colors hover:text-[#a6c8ff]" href="/faq">
              Privacy Policy
            </Link>
            <Link className="font-body text-xs uppercase tracking-widest text-gray-500 transition-colors hover:text-[#a6c8ff]" href="/faq">
              Terms of Service
            </Link>
            <Link className="font-body text-xs uppercase tracking-widest text-gray-500 transition-colors hover:text-[#a6c8ff]" href="/faq">
              Cookie Settings
            </Link>
            <Link className="font-body text-xs uppercase tracking-widest text-gray-500 transition-colors hover:text-[#a6c8ff]" href="/faq">
              Contact
            </Link>
          </div>
        </div>
        <div className="h-1 w-full bg-[#151c25]" />
      </footer>
    </>
  );
}
